services:
  nifi:
    image: apache/nifi:1.23.2
    container_name: nifi
    ports:
      - "8090:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=
      - NIFI_WEB_PROXY_CONTEXT_PATH=
      - NIFI_SECURITY_MODE=UNSECURE
      - NIFI_CLUSTER_IS_NODE=false
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin123

